version: '3'

tasks:
  install-deps:
    desc: Install project dependencies
    cmds:
      - |
        OS=$(uname)
        case "$OS" in
          Linux)
            curl -LsSf https://astral.sh/uv/install.sh | sh
            sudo apt update
            sudo apt install -y flutter
            ;;
          Darwin)
            curl -LsSf https://astral.sh/uv/install.sh | sh
            brew install flutter
            ;;
          *)
            echo "Unsupported OS: $OS"
            exit 1
            ;;
        esac