import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Language = "ru" | "en";

const LANGUAGE_STORAGE_KEY = "trip-planner-language";

export const translations = {
  ru: {
    common: {
      brand: "AI Trip Planner",
      languageSwitchLabel: "Переключить язык интерфейса",
      menu: "Открыть меню",
    },
    sidebar: {
      navigation: "Навигация",
      language: "Язык",
      account: "Аккаунт",
      home: "Главная",
      planner: "Планировщик",
      profile: "Профиль",
      partnerCabinet: "Кабинет партнёра",
      login: "Войти",
      signup: "Регистрация",
      partnerLogin: "Вход для партнёров",
      logout: "Выйти",
      signedInAs: "Вы вошли как",
      accountHint: "Откройте доступ к профилю и персональным маршрутам.",
      guestDescription: "Меню быстрого доступа к основным разделам и входу в аккаунт.",
      authDescription: "Все основные действия и переключение языка теперь собраны в одном месте.",
    },
    hero: {
      partnerButton: "Для партнеров",
      loginButton: "Войти",
      signupButton: "Регистрация",
      aiBadge: "На базе ИИ",
      titlePrefix: "Планируйте своё идеальное",
      titleAccent: "путешествие",
      description:
        "Наш ИИ соберёт персональный маршрут под ваши интересы, бюджет и расписание. Находите места, в которые действительно захочется поехать.",
      primaryAction: "Начать планирование",
      secondaryAction: "О нас",
      travelersStat: "10 000+ довольных путешественников",
      ratingStat: "Рейтинг 4.9/5",
      featuresTitle: "Почему выбирают AI Trip Planner?",

      smartPlanningTitle: "Умное планирование",
      smartPlanningDescription:
        "Маршруты на базе ИИ, собранные под ваши предпочтения.",
      routeOptimizationTitle: "Оптимальные маршруты",
      routeOptimizationDescription:
        "Максимум впечатлений без лишних переездов и потери времени.",
      realtimeUpdatesTitle: "Актуальные обновления",
      realtimeUpdatesDescription:
        "Живые данные и гибкая подстройка расписания по ходу поездки.",
      personalizedTitle: "Персональные рекомендации",
      personalizedDescription:
        "Места и сценарии отдыха, подходящие именно вашему стилю путешествий.",
      trialTitle: "Хотите посмотреть, как это работает?",
      trialDescription:
        "Откройте тестовый планировщик, попробуйте гостевой сценарий и оцените маршрут ещё до регистрации.",
      trialButton: "Попробуйте",
      aboutTitle: "О AI Trip Planner",
      aboutDescription:
        "AI Trip Planner создаёт персональные маршруты с помощью ИИ, оптимизируя путь, время и подбор мест под ваши предпочтения.",
      imageAlt: "Горный пейзаж в лучах солнца",
    },
    login: {
      backHome: "На главную",
      userTitle: "С возвращением",
      userDescription: "Войдите, чтобы продолжить планировать поездки.",
      partnerTitle: "Вход для партнёров",
      partnerDescription: "Используйте данные аккаунта, выданные нашей командой.",
      usernameLabel: "Логин",
      usernamePlaceholder: "Введите логин",
      passwordLabel: "Пароль",
      passwordPlaceholder: "Введите пароль",
      submit: "Войти",
      submitting: "Входим...",
      invalidCredentials: "Неверные данные. Попробуйте ещё раз.",
      noToken: "Не удалось войти: сервер не вернул токен.",
      userSuccess: "Вход выполнен.",
      partnerSuccess: "Вход партнёра выполнен.",
      connectionError: "Ошибка соединения. Попробуйте ещё раз.",
    },
    signup: {
      backHome: "На главную",
      title: "Создание аккаунта",
      basicInformation: "Основная информация",
      travelPreferences: "Параметры поездок",
      nameLabel: "Имя",
      namePlaceholder: "Введите ваше имя",
      emailLabel: "Email",
      emailPlaceholder: "Введите email",
      passwordLabel: "Пароль",
      passwordPlaceholder: "Придумайте надёжный пароль",
      continue: "Далее к предпочтениям",
      maxWalkingDistanceLabel: "Максимальная дистанция пешком (метры)",
      budgetLevelLabel: "Уровень бюджета",
      ratingThresholdLabel: "Минимальный рейтинг",
      transportModeLabel: "Способ передвижения",
      availableFromLabel: "Доступно с",
      availableUntilLabel: "Доступно до",
      preferredTypesLabel: "Предпочитаемые типы мест",
      breakfastLabel: "Люблю завтракать вне дома",
      back: "Назад",
      createAccount: "Создать аккаунт",
      creatingAccount: "Создаём аккаунт...",
      fillAllFields: "Заполните все обязательные поля.",
      invalidEmail: "Введите корректный email с символом @.",
      invalidPassword:
        "Пароль должен быть не короче 8 символов и содержать заглавную, строчную букву, цифру и спецсимвол.",
      selectPreferredType: "Выберите хотя бы один тип мест.",
      success: "Аккаунт создан.",
      failed: "Не удалось зарегистрироваться. Попробуйте ещё раз.",
      genericValidationError: "Некоторые поля заполнены некорректно. Проверьте форму и попробуйте ещё раз.",
      duplicateEmail: "Пользователь с таким email уже существует.",
      duplicateUsername: "Такое имя пользователя уже занято.",
      invalidNameServer: "Укажите имя пользователя.",
      invalidEmailServer: "Укажите корректный email.",
      invalidPasswordServer: "Проверьте пароль и попробуйте ещё раз.",
      invalidBudgetLevelServer: "Выберите корректный уровень бюджета.",
      invalidRatingThresholdServer: "Выберите корректный минимальный рейтинг.",
      invalidTransportModeServer: "Выберите способ передвижения из списка.",
      invalidAvailabilityServer: "Укажите корректное время доступности.",
      invalidPreferredTypesServer: "Выберите хотя бы один тип мест.",
      invalidStartingPointServer: "Не удалось определить стартовую точку. Попробуйте ещё раз.",
      invalidFieldPrefix: "Проверьте поле",
      connectionError: "Ошибка соединения. Попробуйте ещё раз.",
      stepLabel: "Шаг",
      ofLabel: "из",
    },
    chat: {
      title: "Планировщик поездок по Сочи",
      profile: "Профиль",
      logout: "Выйти",
      chatTab: "Чат",
      mapTab: "Карта",
      routeReady: "Маршрут готов. Нажмите на метки, чтобы посмотреть информацию о местах.",
      guestModeMessage:
        "Сейчас вы в гостевом режиме. Войдите, чтобы получать персональные маршруты.",
      routeFailed: "Не удалось построить маршрут. Попробуйте уточнить запрос.",
      mapsLoadError: "Не удалось загрузить карту.",
      serverError: "Ошибка сервера.",
      connectionError: "Ошибка соединения. Попробуйте ещё раз.",
      planning: "Планируем поездку...",
      inputPlaceholder: "Опишите, какую поездку вы хотите спланировать...",
      mapSignIn: "Войдите, чтобы открыть карту.",
      mapLoading: "Загрузка карты...",
      partnerPanelTitle: "Партнёр: добавить место",
      partnerIdLabel: "ID партнёра",
      placeNameLabel: "Название места",
      addressLabel: "Адрес",
      latitudeLabel: "Широта",
      longitudeLabel: "Долгота",
      typesLabel: "Типы через запятую",
      placeNamePlaceholder: "Название партнёрского места",
      addressPlaceholder: "Сочи, ...",
      latitudePlaceholder: "43.585",
      longitudePlaceholder: "39.723",
      typesPlaceholder: "restaurant, cafe",
      partnerSubmit: "Добавить место",
      partnerSubmitting: "Отправляем...",
      partnerValidationError: "Заполните название места и координаты.",
      partnerSubmitSuccess: "Запрос на добавление места отправлен.",
      suggestedPrompts: [
        "Составь маршрут на один день по Сочи с морскими видами и уютными кафе",
        "Построй пеший маршрут по Сочи с парками, смотровыми площадками и локальной едой",
        "Собери семейный маршрут по Сочи с пляжами, развлечениями и местами для детей",
        "Запланируй активный день в Сочи со спортом, природой и ужином вечером",
        "Сделай маршрут по Сочи с акцентом на партнёрские места и локальный опыт",
        "Придумай романтический вечерний маршрут по Сочи с закатом и ужином",
        "Собери гастрономический маршрут по Сочи с завтраком, обедом и ужином",
        "Создай спокойный маршрут по Сочи с прогулками по набережной и кофе-паузами",
        "Сделай культурный маршрут по Сочи с музеями и историческими местами",
        "Построй маршрут по Сочи для шопинга с рынками и lifestyle-локациями",
      ],
    },
    profile: {
      loadError: "Не удалось загрузить профиль.",
      updateSuccess: "Изменения сохранены.",
      updateError: "Не удалось сохранить изменения.",
      loading: "Загрузка профиля...",
      back: "Назад",
      userInfo: "Пользователь",
      username: "Имя пользователя",
      email: "Email",
      preferences: "Предпочтения",
      startingPoint: "Точка старта",
      availability: "Доступность",
      cancel: "Отмена",
      edit: "Изменить",
      apply: "Сохранить",
      maxWalkingDistance: "Максимальная дистанция пешком",
      budgetLevel: "Уровень бюджета",
      ratingThreshold: "Минимальный рейтинг",
      transportMode: "Транспорт",
      breakfastOutside: "Завтрак вне дома",
      yes: "Да",
      no: "Нет",
      name: "Название",
      city: "Город",
      country: "Страна",
      startTime: "Время начала",
      endTime: "Время окончания",
      notSpecified: "Не указано",
      metersShort: "м",
    },
    partnerPlaces: {
      loadError: "Не удалось загрузить ваши места.",
      externalIdError: "Не удалось сгенерировать внешний ID.",
      createError: "Не удалось создать место.",
      linkError: "Не удалось привязать место к партнёру.",
      sessionExpired: "Сессия партнёра истекла. Войдите снова.",
      fillRequiredFields: "Заполните название, категорию и координаты.",
      invalidNumbers: "Широта и долгота должны быть корректными числами.",
      invalidNumbersWithPriority:
        "Координаты и вес приоритета должны быть корректными числами.",
      addSuccess: "Партнёрское место добавлено в базу.",
      addError: "Не удалось добавить партнёрское место.",
      updateSuccess: "Место обновлено.",
      updateError: "Не удалось обновить место.",
      archivedSuccess: "Место отправлено в архив.",
      statusSuccess: "Статус обновлён.",
      statusError: "Не удалось обновить статус.",
      promotionEnabled: "Продвижение включено.",
      promotionDisabled: "Продвижение выключено.",
      promotionError: "Не удалось обновить статус продвижения.",
      confirmArchivePrefix: "Архивировать",
      confirmArchiveSuffix:
        "Его всё равно можно будет увидеть позже в списке.",
      pageTitle: "Кабинет партнёра",
      pageDescription:
        "Добавляйте новые места, просматривайте текущий список и управляйте продвижением.",
      logout: "Выйти",
      addTitle: "Добавить новое место партнёра",
      addDescription:
        "Место автоматически привяжется к партнёру, который сейчас вошёл в систему.",
      placeName: "Название места",
      placeNamePlaceholder: "Название места",
      externalId: "Внешний ID",
      generating: "Генерируем...",
      externalIdPlaceholder: "Будет сгенерирован из названия места",
      externalIdHelp:
        "ID создаётся автоматически по названию и проверяется на уникальность в вашем аккаунте.",
      category: "Категория",
      categoryPlaceholder: "Выберите категорию",
      address: "Адрес",
      addressPlaceholder: "Адрес в Сочи",
      latitude: "Широта",
      longitude: "Долгота",
      addButton: "Добавить в БД",
      addingButton: "Добавляем...",
      yourPlaces: "Ваши места",
      yourPlacesDescription:
        "Просматривайте все места, связанные с партнёрским аккаунтом, и управляйте их поведением.",
      refresh: "Обновить",
      refreshing: "Обновляем...",
      listLoading: "Загружаем ваши места...",
      empty: "У вас пока нет мест. Добавьте первое место выше.",
      unnamedPlace: "Без названия",
      addressNotSet: "Адрес не указан",
      priority: "Приоритет",
      promotionOn: "Продвижение включено",
      promotionOff: "Продвижение выключено",
      edit: "Изменить",
      enablePromo: "Включить промо",
      disablePromo: "Выключить промо",
      saving: "Сохраняем...",
      pause: "Пауза",
      activate: "Активировать",
      restore: "Восстановить",
      archive: "В архив",
      editTitle: "Редактировать место",
      editDescription:
        "Обновите данные места и настройки продвижения для этой партнёрской локации.",
      status: "Статус",
      statusPlaceholder: "Выберите статус",
      priorityWeight: "Вес приоритета",
      promotion: "Продвижение",
      promotionDescription:
        "Разрешить показывать это место в партнёрских рекомендациях.",
      cancel: "Отмена",
      saveChanges: "Сохранить изменения",
    },
    notFound: {
      title: "Страница не найдена",
      action: "Вернуться на главную",
    },
    map: {
      unknownPlace: "Неизвестное место",
    },
  },
  en: {
    common: {
      brand: "AI Trip Planner",
      languageSwitchLabel: "Switch interface language",
      menu: "Open menu",
    },
    sidebar: {
      navigation: "Navigation",
      language: "Language",
      account: "Account",
      home: "Home",
      planner: "Planner",
      profile: "Profile",
      partnerCabinet: "Partner Panel",
      login: "Log In",
      signup: "Sign Up",
      partnerLogin: "Partner Sign In",
      logout: "Logout",
      signedInAs: "Signed in as",
      accountHint: "Sign in to unlock your profile and personalized itineraries.",
      guestDescription: "Quick access to the main sections and authentication actions.",
      authDescription: "Core account actions and language controls are grouped here for quick access.",
    },
    hero: {
      partnerButton: "For Partners",
      loginButton: "Log In",
      signupButton: "Sign Up",
      aiBadge: "Powered by AI",
      titlePrefix: "Plan Your Perfect",
      titleAccent: "Adventure",
      description:
        "Let our AI create personalized travel itineraries that match your interests, budget, and schedule. Discover amazing places you'll love.",
      primaryAction: "Start Planning Now",
      secondaryAction: "About us",
      travelersStat: "10,000+ Happy Travelers",
      ratingStat: "4.9/5 Rating",
      featuresTitle: "Why Choose AI Trip Planner?",
      smartPlanningTitle: "Smart Planning",
      smartPlanningDescription:
        "AI-powered itineraries tailored to your preferences.",
      routeOptimizationTitle: "Route Optimization",
      routeOptimizationDescription:
        "Efficient routes that maximize your travel time.",
      realtimeUpdatesTitle: "Real-time Updates",
      realtimeUpdatesDescription:
        "Live information and dynamic schedule adjustments.",
      personalizedTitle: "Personalized",
      personalizedDescription:
        "Recommendations based on your unique travel style.",
      trialTitle: "Want to see how it works?",
      trialDescription:
        "Open the trial planner, try the guest flow, and preview your route before creating an account.",
      trialButton: "Try It",
      aboutTitle: "About AI Trip Planner",
      aboutDescription:
        "AI Trip Planner creates personalized itineraries using AI, optimizing routes, time, and preferences.",
      imageAlt: "Mountain landscape hit by sun rays",
    },
    login: {
      backHome: "Back to Home",
      userTitle: "Welcome Back",
      userDescription: "Sign in to continue planning your trips.",
      partnerTitle: "Partner Sign In",
      partnerDescription: "Sign in with the account issued by our team.",
      usernameLabel: "Username",
      usernamePlaceholder: "Enter your username",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter your password",
      submit: "Sign In",
      submitting: "Signing in...",
      invalidCredentials: "Invalid credentials. Please try again.",
      noToken: "Login failed: no token returned.",
      userSuccess: "Login successful.",
      partnerSuccess: "Partner login successful.",
      connectionError: "Connection error. Please try again.",
    },
    signup: {
      backHome: "Back to Home",
      title: "Create Your Account",
      basicInformation: "Basic Information",
      travelPreferences: "Travel Preferences",
      nameLabel: "Name",
      namePlaceholder: "Enter your full name",
      emailLabel: "Email",
      emailPlaceholder: "Enter your email address",
      passwordLabel: "Password",
      passwordPlaceholder: "Create a secure password",
      continue: "Continue to Preferences",
      maxWalkingDistanceLabel: "Max Walking Distance (meters)",
      budgetLevelLabel: "Budget Level",
      ratingThresholdLabel: "Rating Threshold",
      transportModeLabel: "Transport Mode",
      availableFromLabel: "Available From",
      availableUntilLabel: "Available Until",
      preferredTypesLabel: "Preferred Place Types",
      breakfastLabel: "I like having breakfast outside",
      back: "Back",
      createAccount: "Create Account",
      creatingAccount: "Creating Account...",
      fillAllFields: "Please fill in all fields.",
      invalidEmail: "Please enter a valid email address with @ symbol.",
      invalidPassword:
        "Password must be at least 8 characters with uppercase, lowercase, number and special character.",
      selectPreferredType: "Please select at least one preferred type.",
      success: "Account created successfully.",
      failed: "Registration failed. Please try again.",
      genericValidationError: "Some fields are filled in incorrectly. Please review the form and try again.",
      duplicateEmail: "An account with this email already exists.",
      duplicateUsername: "This username is already taken.",
      invalidNameServer: "Please enter a username.",
      invalidEmailServer: "Please enter a valid email address.",
      invalidPasswordServer: "Please check the password and try again.",
      invalidBudgetLevelServer: "Please choose a valid budget level.",
      invalidRatingThresholdServer: "Please choose a valid rating threshold.",
      invalidTransportModeServer: "Please choose a transport mode from the list.",
      invalidAvailabilityServer: "Please enter a valid availability time.",
      invalidPreferredTypesServer: "Please choose at least one preferred place type.",
      invalidStartingPointServer: "Couldn't determine the starting point. Please try again.",
      invalidFieldPrefix: "Please check the field",
      connectionError: "Connection error. Please try again.",
      stepLabel: "Step",
      ofLabel: "of",
    },
    chat: {
      title: "Sochi Trip Planner",
      profile: "Profile",
      logout: "Logout",
      chatTab: "Chat",
      mapTab: "Map",
      routeReady: "I've planned your route! Click on markers to see place info.",
      guestModeMessage:
        "You're in guest mode. Sign in to unlock personalized routes.",
      routeFailed: "I couldn't generate a route. Try being more specific.",
      mapsLoadError: "Failed to load maps.",
      serverError: "Server error.",
      connectionError: "Connection error. Please try again.",
      planning: "Planning your trip...",
      inputPlaceholder: "Describe your trip plans...",
      mapSignIn: "Sign in to view the map.",
      mapLoading: "Loading map...",
      partnerPanelTitle: "Partner: Add Place",
      partnerIdLabel: "Partner ID",
      placeNameLabel: "Place Name",
      addressLabel: "Address",
      latitudeLabel: "Latitude",
      longitudeLabel: "Longitude",
      typesLabel: "Types (comma-separated)",
      placeNamePlaceholder: "Partner place name",
      addressPlaceholder: "Sochi, ...",
      latitudePlaceholder: "43.585",
      longitudePlaceholder: "39.723",
      typesPlaceholder: "restaurant, cafe",
      partnerSubmit: "Add Partner Place",
      partnerSubmitting: "Sending...",
      partnerValidationError: "Fill place name and coordinates.",
      partnerSubmitSuccess: "Partner place request sent.",
      suggestedPrompts: [
        "Plan a one-day sightseeing route in Sochi with seaside landmarks and cafes",
        "Build a walking route in Sochi with parks, viewpoints, and local food",
        "Create a Sochi family itinerary with beaches, attractions, and kid-friendly places",
        "Plan an active day in Sochi with sports, nature, and evening restaurants",
        "Create a Sochi route focused on partner places and local experiences",
        "Design a romantic Sochi evening route with sunset and dinner spots",
        "Build a food-focused Sochi route with breakfast, lunch, and dinner places",
        "Create a relaxed Sochi route with promenade walks and coffee stops",
        "Plan a Sochi cultural route with museums and historical places",
        "Build a Sochi shopping route with markets and lifestyle locations",
      ],
    },
    profile: {
      loadError: "Failed to load profile.",
      updateSuccess: "Updated successfully.",
      updateError: "Failed to update profile.",
      loading: "Loading profile...",
      back: "Back",
      userInfo: "User Info",
      username: "Username",
      email: "Email",
      preferences: "Preferences",
      startingPoint: "Starting Point",
      availability: "Availability",
      cancel: "Cancel",
      edit: "Edit",
      apply: "Apply",
      maxWalkingDistance: "Max walking distance",
      budgetLevel: "Budget level",
      ratingThreshold: "Rating threshold",
      transportMode: "Transport mode",
      breakfastOutside: "Breakfast outside",
      yes: "Yes",
      no: "No",
      name: "Name",
      city: "City",
      country: "Country",
      startTime: "Start time",
      endTime: "End time",
      notSpecified: "Not specified",
      metersShort: "m",
    },
    partnerPlaces: {
      loadError: "Failed to load your places.",
      externalIdError: "Failed to generate external ID.",
      createError: "Failed to create place.",
      linkError: "Failed to link partner place.",
      sessionExpired: "Partner session expired. Please sign in again.",
      fillRequiredFields: "Fill name, category and coordinates.",
      invalidNumbers: "Latitude and longitude must be valid numbers.",
      invalidNumbersWithPriority:
        "Coordinates and priority weight must be valid numbers.",
      addSuccess: "Partner place added to database.",
      addError: "Failed to add partner place.",
      updateSuccess: "Place updated.",
      updateError: "Failed to update place.",
      archivedSuccess: "Place archived.",
      statusSuccess: "Status updated.",
      statusError: "Failed to update status.",
      promotionEnabled: "Promotion enabled.",
      promotionDisabled: "Promotion disabled.",
      promotionError: "Failed to update promotion status.",
      confirmArchivePrefix: "Archive",
      confirmArchiveSuffix:
        "You can still see it later in the list.",
      pageTitle: "Partner Panel",
      pageDescription:
        "Add new places, review your current inventory, and manage what is promoted.",
      logout: "Logout",
      addTitle: "Add New Partner Place",
      addDescription:
        "The place will be linked to the currently signed-in partner automatically.",
      placeName: "Place Name",
      placeNamePlaceholder: "Place name",
      externalId: "External ID",
      generating: "Generating...",
      externalIdPlaceholder: "Generated from place name",
      externalIdHelp:
        "Generated automatically from the place name and checked for uniqueness in your account.",
      category: "Category",
      categoryPlaceholder: "Select a category",
      address: "Address",
      addressPlaceholder: "Sochi address",
      latitude: "Latitude",
      longitude: "Longitude",
      addButton: "Add place to DB",
      addingButton: "Adding...",
      yourPlaces: "Your Places",
      yourPlacesDescription:
        "Review all places linked to your partner account and manage how they behave.",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      listLoading: "Loading your places...",
      empty: "You do not have any places yet. Add your first place above.",
      unnamedPlace: "Unnamed place",
      addressNotSet: "Address not set",
      priority: "Priority",
      promotionOn: "Promotion on",
      promotionOff: "Promotion off",
      edit: "Edit",
      enablePromo: "Enable Promo",
      disablePromo: "Disable Promo",
      saving: "Saving...",
      pause: "Pause",
      activate: "Activate",
      restore: "Restore",
      archive: "Archive",
      editTitle: "Edit Place",
      editDescription:
        "Update the place data and promotion settings for this partner location.",
      status: "Status",
      statusPlaceholder: "Select a status",
      priorityWeight: "Priority Weight",
      promotion: "Promotion",
      promotionDescription:
        "Allow this place to appear in partner recommendations.",
      cancel: "Cancel",
      saveChanges: "Save changes",
    },
    notFound: {
      title: "Oops! Page not found",
      action: "Return to Home",
    },
    map: {
      unknownPlace: "Unknown place",
    },
  },
} as const;

type TranslationCopy = (typeof translations)[Language];

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  copy: TranslationCopy;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") {
      return "ru";
    }

    const savedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return savedLanguage === "en" || savedLanguage === "ru" ? savedLanguage : "ru";
  });

  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: setLanguageState,
        copy: translations[language],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return context;
}
